routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/generate-users', function () {
    //this can be used to generate users
    $users = factory(MailChimp\User::class, 50)->create();
    echo "users generated";
});

Auth::routes();
Route::get('/lists/{list}/members/create', 'MembersController@create')->name('lists.members.create');
Route::get('/members/{member}/edit', 'MembersController@edit')->name('lists.members.edit');

Route::resource('/lists', 'MailListsController');

Route::post('lists/{list}/members/store', 'MembersController@store')->name('members.store');
Route::patch('/members/{member}/update', 'MembersController@update')->name('members.update');
Route::delete('/members/{member}/destroy', 'MembersController@destroy')->name('members.destroy');

resources/views/lists/create.blade.php
@extends('layouts.master')
@section('content')

  <div class="container-fluid id="app"">
        <div class="animated fadeIn">
          <div class="row">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-header">
                  <strong>Lists</strong>
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-12">
                      @if ($errors->any())
                      <ul class="alert alert-danger">
                          @foreach ($errors->all() as $error)
                              <li>{{ $error }}</li>
                          @endforeach
                      </ul>
                  @endif

                  {!! Form::open(['route' => 'lists.store', 'class' => 'form-horizontal']) !!}

                  @include ('lists.form')

                  {!! Form::close() !!}

                    </div>

                  </div>
                  <!--/.row-->
                </div>
              </div>

            </div>
            <!--/.col-->

@endsection

resources/views/lists/edit.blade.php
@extends('layouts.master')
@section('content')

  <div class="container-fluid">
        <div class="animated fadeIn">
          <div class="row">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-header">
                  <strong>Edit List - {{$record->name}}</strong>
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-12">
                          @if ($errors->any())
                              <ul class="alert alert-danger">
                                  @foreach ($errors->all() as $error)
                                      <li>{{ $error }}</li>
                                  @endforeach
                              </ul>
                          @endif

                          {!! Form::model($record, [
                              'method' => 'PATCH',
                              'route' => ['lists.update', $record->id],
                              'class' => 'form-horizontal',
                              'files' => 'true'
                          ]) !!}
                          @include ('lists.form', ['submitButtonText' => 'Update'])
                          {!! Form::close() !!}
                    </div>

                  </div>
                  <!--/.row-->
                </div>
              </div>

            </div>
            <!--/.col-->

@endsection

resources/views/lists/form.blade.php
<div class="form-group">
  {!! Form::label('name', 'Name', ['class' => 'control-label']) !!}
  {!! Form::text('name', null, ['class' => 'form-control','placeholder' => 'Enter name']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
   {!! Form::label('user_id', 'Contact:', ['class' => 'control-label']) !!}
   {!! Form::select('user_id',MailChimp\Services\DisplayServices::fetchUser(), null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
  {!! Form::label('reminder', 'Permission Reminder', ['class' => 'control-label']) !!}
  {!! Form::text('reminder', 'You are receiving this email because you signed up for it', ['class' => 'form-control','placeholder' => 'Enter a sentence']) !!}
        {!! $errors->first('reminder', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
   {!! Form::label('type_option', 'Let member choose email type:', ['class' => 'control-label']) !!}
   {!! Form::select('type_option',['1' => 'Yes', '0' => 'No'], null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
  {!! Form::label('from_name', 'From Name', ['class' => 'control-label']) !!}
  {!! Form::text('from_name', null, ['class' => 'form-control','placeholder' => 'Enter from name']) !!}
        {!! $errors->first('from_name', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
  {!! Form::label('from_email', 'From email', ['class' => 'control-label']) !!}
  {!! Form::text('from_email', null, ['class' => 'form-control','placeholder' => 'Enter from email']) !!}
        {!! $errors->first('from_email', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
  {!! Form::label('subject', 'Subject', ['class' => 'control-label']) !!}
  {!! Form::text('subject', null, ['class' => 'form-control','placeholder' => 'Enter Subject']) !!}
        {!! $errors->first('subject', '<p class="help-block">:message</p>') !!}
</div>


<div class="form-group text-right">
        {!! Form::submit(isset($submitButtonText) ? $submitButtonText : 'Create', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/lists/index.blade.php
@extends('layouts.master')
@section('content')
<div class="starter-template">
  <div class="row">
      <div class="col-9">
            <h1>Lists</h1>
      </div>
      <div class="col-3">
            <a class="btn btn-success" href="{{route('lists.create')}}">New List</a>
      </div>
  </div>

  <div class="row">
      <div class="col-12">
        @if (Session::has('message'))
                 <div class="alert {{Session::get('code')}} alert-dismissable fade show" role="alert">
                   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                   </button>
                   <h4>{{ Session::get('message') }}</h4>
                 </div>
        @endif
      </div>
  </div>
  <div class="row">
      <div class="col-3"><strong>Name</strong></div>
      <div class="col-2"><strong>contact</strong></div>
      <div class="col-3"><strong>subject</strong></div>
      <div class="col-4"></div>
  </div>

  @foreach ($records as $record)
    <div class="row">
        <div class="col-3">{{ $record->name }}</div>
        <div class="col-2">{{ $record->contact->name }}</div>
        <div class="col-3">{{ $record->subject }}</div>
        <div class="col-4">
           <a class="btn btn-warning btn-sm" href="{{route('lists.show', $record->id)}}">Members</a>
           <a class="btn btn-primary btn-sm" href="{{route('lists.edit', $record->id)}}">Edit</a>
           {!! Form::open([
               'method'=>'DELETE',
               'route' => ['lists.destroy', $record->id],
               'style' => 'display:inline'
           ]) !!}
               {!! Form::button('<span>  Delete </span>', array(
                       'type' => 'submit',
                       'class' => 'btn btn-danger btn-sm',
                       'title' => 'Delete List',
                       'onclick'=>'return confirm("Confirm delete?")'
               )) !!}
           {!! Form::close() !!}
        </div>
    </div>
  @endforeach
  {{ $records->links() }}

</div>
@endsection

resources/views/lists/show.blade.php
@extends('layouts.master')
@section('content')
<div class="starter-template">
  <div class="row">
      <div class="col-12">
        @if (Session::has('message'))
                 <div class="alert {{Session::get('code')}} alert-dismissable fade show" role="alert">
                   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                   </button>
                   <h4>{{ Session::get('message') }}</h4>
                 </div>
        @endif
      </div>
  </div>
  <div class="row">
        <div class="col-4"><strong>Name</strong></div>
        <div class="col-8">{{$record->name}}</div>
  </div>
  <div class="row">
        <div class="col-4"><strong>Contact</strong></div>
        <div class="col-8">{{$record->contact->name}}, {{$record->contact->company}}</div>
  </div>
  <div class="row">
        <div class="col-4"><strong>Subject</strong></div>
        <div class="col-8">{{$record->subject}}</div>
  </div>
  <div class="row">
        <div class="col-4"><strong>MailChimp Admin URL</strong></div>
        <div class="col-8"><a target='_blank' href="https://{{ MailChimp\Services\DisplayServices::fetchDataCenter()}}.admin.mailchimp.com/lists/members/?id={{ $record->mailchimp_webid}}">
          https://{{ MailChimp\Services\DisplayServices::fetchDataCenter()}}.admin.mailchimp.com/lists/members/?id={{ $record->mailchimp_webid}}
        </a></div>
  </div>
</div>
<div class="members" style="border-top:.1rem brown solid;margin-top:1rem;">
  <div class="row">
        <div class="col-8"><h4>Members</h4></div>
        <div class="col-4"><a class="btn btn-lg btn-success" href="{{route('lists.members.create', $record->id)}}">Add Member</a></div>
  </div>
  <div class="row">
      <div class="col-4"><strong>Name</strong></div>
      <div class="col-4"><strong>email</strong></div>
  </div>
  @foreach ($record->members as $member)
    <div class="row">
          <div class="col-4">{{$member->firstname}} {{$member->lastname}}</div>
          <div class="col-4">{{$member->email}}</div>
          <div class="col-4">
            <a class="btn btn-primary btn-sm" href="{{route('lists.members.edit', $member->id)}}">Edit</a>
            {!! Form::open([
                'method'=>'DELETE',
                'route' => ['members.destroy', $member->id],
                'style' => 'display:inline'
            ]) !!}
                {!! Form::button('<span>  Delete </span>', array(
                        'type' => 'submit',
                        'class' => 'btn btn-danger btn-sm',
                        'title' => 'Delete Member',
                        'onclick'=>'return confirm("Confirm delete?")'
                )) !!}
            {!! Form::close() !!}

          </div>
    </div>
  @endforeach

</div>
@endsection